### ISSUE TITLE
Failing with Ansible 2.0.2.0 - template error unexpected char

### ISSUE THREAD

**Issue by jagregory-myob** [ANXS/apt#11]
```
FAILED! => {"failed": true, "msg": "The conditional check ''0 upgraded' failed.
  The error was: template error while templating string: unexpected char u\"'\" at 6.
  String: {% if '0 upgraded %} True {% else %} False {% endif %}"}
```

Looks like something to do with templating has changed between 2.0.0.0 and 2.0.2.0.

**Comment by jagregory-myob** [comment]
This appears to be related to the comma in the `changed_when` string: `0 upgraded, 0 newly installed, 0 to remove`.

I can work around this by extracting the whole string into a variable and checking against that.

```yaml
changed_when: "'{{apt_nothing_changed_text}}' not in autoremove_output.stdout and 'not upgraded' not in autoremove_output.stdout"
```

**Comment by otakup0pe** [comment]
Weird. It's not failing for me, although I get plenty of deprecation warnings.

**Comment by otakup0pe** [comment]
With #14 the minimum version is 2.3.2 so closing this out...
